# Generated by Django 2.0.1 on 2018-01-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='Телефон')),
                ('type', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Тип заявки')),
                ('text', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Комментарий')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Была оставлена')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
