# Generated by Django 2.0.1 on 2018-01-20 03:54

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('subj', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('text', tinymce.models.HTMLField()),
                ('video_iframe', models.TextField(blank=True, default=None, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='RepliesImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/replies')),
                ('reply', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.Replies')),
            ],
            options={
                'verbose_name': 'Фото на отзыв',
                'verbose_name_plural': 'Фото на отзывы',
            },
        ),
    ]
