# Generated by Django 2.0.1 on 2018-01-20 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_replies_repliesimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, max_length=124, null=True)),
            ],
            options={
                'verbose_name': 'Цены, категория',
                'verbose_name_plural': 'Цены, категории',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj', models.TextField(blank=True, default=None, max_length=256, null=True)),
                ('price', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('prices_cat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.PriceHead')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
