# Generated by Django 2.0.1 on 2018-01-21 11:42

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_pricehead_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=56, null=True, verbose_name='Имя')),
                ('job', models.CharField(blank=True, default=None, max_length=56, null=True, verbose_name='Должность')),
                ('e1', tinymce.models.HTMLField(default=None, verbose_name='Дополнительное поле 1 (стаж)')),
                ('e2', tinymce.models.HTMLField(default=None, verbose_name='Дополнительное поле 2 (выиграно дел)')),
                ('e3', tinymce.models.HTMLField(default=None, verbose_name='Дополнительное поле 3 (отрасль)')),
                ('text', tinymce.models.HTMLField(default=None, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='StuffImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/img/stuff')),
                ('stuff', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.Stuff')),
            ],
        ),
    ]
