# Generated by Django 2.0.1 on 2018-01-20 12:11

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('url_name', models.CharField(blank=True, default=None, max_length=70, null=True)),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
            },
        ),
        migrations.CreateModel(
            name='CategoryImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/categories')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Category')),
            ],
            options={
                'verbose_name': 'Фото категории услуг',
                'verbose_name_plural': 'Фото категорий услуг',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Пакет документов',
                'verbose_name_plural': 'Пакет документов',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('meta_tags', models.TextField(blank=True, default=None, max_length=256, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('block1_header', tinymce.models.HTMLField(default=None)),
                ('block2_header', tinymce.models.HTMLField(default=None)),
                ('block2_text', tinymce.models.HTMLField(default=None)),
                ('block3_header', tinymce.models.HTMLField(default=None)),
                ('price', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('price_descriptor', tinymce.models.HTMLField(default=None)),
                ('url_name', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Category')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceComplexText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField()),
                ('service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'verbose_name': 'Комплекс услуг',
                'verbose_name_plural': 'Комплекс услуг',
            },
        ),
        migrations.CreateModel(
            name='ServiceImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='static/img/categories')),
                ('service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'verbose_name': 'Фото услуги',
                'verbose_name_plural': 'Фото услуг',
            },
        ),
        migrations.AddField(
            model_name='documents',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
    ]
