# Generated by Django 2.0.1 on 2018-01-21 02:36

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='page_title',
            field=models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Заголовок в браузере'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url_name',
            field=models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='URL страницы в адресной строке'),
        ),
        migrations.AlterField(
            model_name='service',
            name='block1_header',
            field=tinymce.models.HTMLField(default=None, verbose_name='Заголовок первого блока'),
        ),
        migrations.AlterField(
            model_name='service',
            name='block2_header',
            field=tinymce.models.HTMLField(default=None, verbose_name='Заголовок второго блока'),
        ),
        migrations.AlterField(
            model_name='service',
            name='block2_text',
            field=tinymce.models.HTMLField(default=None, verbose_name='Текст второго блока'),
        ),
        migrations.AlterField(
            model_name='service',
            name='block3_header',
            field=tinymce.models.HTMLField(default=None, verbose_name='Заголовок третьего блока'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_tags',
            field=models.TextField(blank=True, default=None, max_length=256, null=True, verbose_name='Мета теги (для CEO)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='page_title',
            field=models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Заголовок в браузере'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_descriptor',
            field=tinymce.models.HTMLField(default=None, verbose_name='Постскриптор в блоке цены'),
        ),
        migrations.AlterField(
            model_name='service',
            name='url_name',
            field=models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='URL страницы в адресной строке'),
        ),
    ]
